//
// Copyright (c) 2021 - Yupiik SAS - https://www.yupiik.com
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//

= Yupiik uShip

[abstract]
Uship (µship) is a lightweight microservice stack for modern applications.

== Pre-requisites

. Ensure to use java >= 11
. (Optional) Ensure to use a dependency manager such as Apache Maven/Gradle/SBT or Apache Ivy.

TIP: using link:https://sdkman.io/[SDKMan] can greatly simplify the installation.

== Development stack

The goal of µShip is to promote and enable JSON-RPC development at scale.
For that it provides a CDI-Servlet integration module known as `jsonrpc-core` module.

However, µShip also provides all the underlying stack to make it functional such as:

* An embedded Servlet container (Apache Tomcat),
* JSON-P/JSON-B integration modules,
* JSON-RPC API/implementation and documentation utilities.

TIP: as of today, µShip does not go further - as providing a configuration/openmetrics/opentracing/JWT integration since these ones can easily be added using CDI libraries.
It will probably be tackled in a few versions but was not a pre-requisite of the project.

== Documentation

You can learn more by reading the link:https://yupiik.github.io/uship/[online documentation].
