= HTTP Client

UShip HTTP Client is based on `java.net.http.HttpClient`.
It is configured with `ExtendedHttpClientConfiguration` which enables to:

- optionally provide a configured `HttpClient` instance - otherwise the default JVM one is used,
- optionally provide a set of `RequestListener`s which listen for requests.

== Request Listeners

Request listener is a callback triggered before and after each request.
It enables to store data before the requests in the caller context and execute some callback once the request is finished.
To pass data between both steps (since the request can be asynchronous or not) it uses a `State` which can hold any data the listener needs.

TIP: if you write custom listeners (to add OpenTracing capabilities for example), you can make them implement `AutoCloseable` and when closing the HTTP client the method will be called automatically.

=== Default Listeners

==== `DefaultTimeout`

This listener is pretty straight forward, if the request does not have a timeout, it sets it to the default one configured in the listener.
It enables to enforce a global timeout to all requests.

==== `SetUserAgent`

This listener enforce a custom user-agent value.
It defaults to chrome one.

==== `ExchangeLogger`

This listener enables to force all exchanges to be logged.

==== `HARDumperListener`

This listener enables to capture a `HAR` dump of all exchanges which went through the client.
It can be very useful to generate some test data you replay with a HAR server in a test or a demo environment.

=== Sample usage

[source,java]
----
final var conf = new ExtendedHttpClientConfiguration();

// (optional) force a custom SSL context
conf.setDelegate(
    HttpClient.newBuilder()
        .sslContext(getSSLContext())
        .build());

// (optional) force custom listeners
conf.setListeners(List.of(
        new AutoTimeoutSetter(Duration.ofSeconds(3600)),
        new AutoUserAgentSetter(),
        new ExchangeLogger(
            Logger.getLogger(getClass().getName()),
            Clock.systemUTC(),
            false)));
----

== Kubernetes client

`kubernetes-client` modules providers a HTTP Client already configured for Kubernetes in cluster connection (from a POD).
This will typically be used from an operator or cloud native application to call Kubernetes API using a plain and very light HTTP Client from the JVM.

TIP: indeed you can combine it with the enhanced HTTP Client configuring it in the `KubernetesClientConfiguration`.
However, it is recommended to do it using `setClientWrapper` on the configuration and pass the automatically created client to `ExtendedHttpClientConfiguration.setDelegate`
to avoid to have to handle the `SSLContext` yourself.

Usage:

[source,java]
----
final var conf = new KubernetesClientConfiguration()
    .setClientWrapper(client -> new ExtendedHttpClient(new ExtendedHttpClientConfiguration()
        .setDelegate(client)));
final var k8s = new KubernetesClient(conf);

// now call any API you need:
final var response = k8s.send(
        HttpRequest.newBuilder()
                .GET()
                .uri(URI.create(
                    "https://kubernetes.api/api/v1/namespaces/" + k8s.namespace().orElse("default") + "/configmaps?" +
                            "includeUninitialized=false&" +
                            "limit=1000&" +
                            "timeoutSeconds=600")
                .header("Accept", "application/json")
                .build(),
        HttpResponse.BodyHandlers.ofString(StandardCharsets.UTF_8));
// handle the response
----

IMPORTANT: as you can see, there is no need to pass the token to the request, it is done under the hood by the `KubernetesClient`.
The other important note is that `https://kubernetes.api` is automatically replaced by the `conf.getMaster()` value.
This enables your code to stay more straight forward in general but if you pass them, the client will handle it properly too.

== JSON-RPC client

As a JSON-RPC server companion UShip also provides a JSON-RPC client.

[source,xml]
----
<dependency>
  <groupId>io.yupiik.uship</groupId>
  <artifactId>jsonrpc-client</artifactId>
  <version>${uship.version}</version>
</dependency>
----

The minimum configuration is to provide the JSON-RPC endpoint:

[source,java]
----
final var client = new JsonRpcClient(new JsonRpcClientConfiguration("http://app.service.com/jsonrpc"));
----

But more is customizable in `JsonRpcClientConfiguration` and a common initialization would look like:

[source,java]
----
@Produces
@ApplicationScoped
public ExtendedHttpClient jsonRpcHttpClient() {
    return ...; // create it as usual
}

public void releaseHttpClient(@Disposes final ExtendedHttpClient client) {
    client.close();
}

@Produces
@ApplicationScoped
public JsonRpcClient jsonRpcClient(
            // external config
            @ConfigProperty("jsonrpc.base") final String base,
            @ConfigProperty("jsonrpc.authorizationheader") final String auth,
            // from uship json in general
            final JsonBuilderFactory jbf, final Jsonb jsonb,
            // created in the app (other producer)
            final ExtendedHttpClient client) {
    return new JsonRpcClient(new JsonRpcClientConfiguration(base + "/jsonrpc"))
        // all these setters are optional but enables to use controlled instances (vs implicit) and optimize/customize the behavior/mem/security
        .setJsonBuilderFactory(jbf)
        .setJsonb(jsonb)
        .setHttpClient(client) // enables to customize the async thread pool for example (highly encourage for executeAsync usage)
        .setRequestCustomizer(req -> req.header("authorization", auth));
}

public void releaseJsonRpcClient(@Disposes final JsonRpcClient client) {
    client.close();
}
----

Then you can simply use it in your application:

[source,java]
----
@ApplicationScoped
public class MyService {
    @Inject
    private JsonRpcClient client;

    public CompletionStage<Customer> findCustomer(final String id) {
        return client.executeAsync("app-customer-find-by-id", Map.of("id", id))
            // todo: better error handling if needed
            .thenApply(r -> r.asSingle().as(Customer.class));
    }
}
----
